Fix :func:`anext` failing on sync :meth:`~object.__anext__` raising an exception.
